# Generated by Django 4.2 on 2024-11-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=250)),
                ("key", models.CharField(max_length=50, unique=True)),
                ("views", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
